### PR TITLE
feat(host/uvc): generic unit and terminal control API (IEC-608)

### PR DESCRIPTION
**Pull request by ak1932**
## Description

There is currently no way to reach a control this driver does not implement itself.
Anything beyond probe and commit needs the device handle and the VideoControl interface
number, both private, so applications either patch the driver or go without.

That matters most for Extension Units, whose payloads are vendor-defined and which the
driver therefore cannot interpret for the caller. It also covers the standard Camera
Terminal and Processing Unit controls, which are policy rather than stream operations:
whether auto-exposure may trade frame rate for exposure is the application's call.

```c
uvc_host_stream_send_custom_request()    // raw class request, mirrors cdc_acm_host
uvc_host_stream_find_extension_unit()    // by GUID, since unit IDs are per-camera
uvc_host_stream_find_terminal()          // by wTerminalType
uvc_host_stream_unit_supports_control()  // bmControls capability check
uvc_host_stream_unit_ctrl()              // VideoControl unit or terminal
uvc_host_stream_vs_ctrl()                // raw VideoStreaming escape hatch
uvc_host_stream_request_key_frame()      // VS Generate Key Frame (second commit)
```

`uvc_host_stream_unit_ctrl()` composes `wValue` and `wIndex` from the selector and unit ID,
which is the part callers get wrong by hand. The capability check is not defensive noise: a
camera lacking a control answers with a STALL, which USBH logs at ERROR, so an
unconditional write puts an error in the log of every boot.

The VideoStreaming interface belongs to this driver, so every control 
the spec defines there is the driver's to implement with its capability check built
in — `uvc_host_stream_request_key_frame()` is the worked example, and
`uvc_host_stream_vs_ctrl()` is documented as an escape hatch for vendor-specific selectors,
not the intended path. The VideoControl side is the opposite: generic access, because an
Extension Unit payload is not something the driver can know.

Nothing H.264-specific is added. The consumer that motivated this lives a layer up and expected to land in
`esp_video`, where the H.264 payload spec's vocabulary belongs. It would bring controls to set bitrate for h.264 and controls like set auto exposure, set frame interval.

An example set auto exposure (ae) priority function (to be upstreamed to esp_video once this PR lands) can be 

```c
esp_err_t esp_video_uvc_set_ae_priority(uvc_host_stream_hdl_t stream_hdl, uint8_t priority,
                                             uint8_t *committed)
{
    ESP_RETURN_ON_FALSE(stream_hdl, ESP_ERR_INVALID_ARG, TAG, "stream_hdl is NULL");
    ESP_RETURN_ON_FALSE(priority <= 1, ESP_ERR_INVALID_ARG, TAG, "priority must be 0 or 1");

    uint8_t terminal_id = 0;
    bool has_ae_priority = false;

    ESP_RETURN_ON_ERROR(uvc_host_stream_find_terminal(stream_hdl, UVC_HOST_ITT_CAMERA, &terminal_id),
                        TAG, "No Camera Terminal on this camera");
  
    ESP_RETURN_ON_ERROR(uvc_host_stream_unit_supports_control(stream_hdl, terminal_id,
                                                              ESP_VIDEO_UVC_CT_AE_PRIORITY_BIT,
                                                              &has_ae_priority),
                        TAG, "Could not read Camera Terminal controls");

    if (!has_ae_priority) {
        ESP_LOGW(TAG, "Camera Terminal %u does not implement AE Priority - the sensor frame "
                 "rate is not controllable on this camera", terminal_id);
        return ESP_ERR_NOT_SUPPORTED;
    }

    uint8_t value = priority;
    ESP_RETURN_ON_ERROR(uvc_host_stream_unit_ctrl(stream_hdl, terminal_id, UVC_CT_AE_PRIORITY_CONTROL,
                                                  UVC_HOST_REQ_SET_CUR, &value, sizeof(value)),
                        TAG, "AE Priority write rejected");

    /* Read back rather than trust the write: this is the same class of control as the H.264
     * extension unit, where a SET_CUR succeeded and the value was quietly ignored. */
    value = 0xff;
    ESP_RETURN_ON_ERROR(uvc_host_stream_unit_ctrl(stream_hdl, terminal_id, UVC_CT_AE_PRIORITY_CONTROL,
                                                  UVC_HOST_REQ_GET_CUR, &value, sizeof(value)),
                        TAG, "AE Priority read-back failed");

    ESP_LOGI(TAG, "AE Priority on Camera Terminal %u: asked %u, committed %u (%s)",
             terminal_id, priority, value,
             value == 0 ? "constant frame rate - exposure gives way"
             : "frame rate may vary - exposure wins");
    if (value != priority) {
        ESP_LOGW(TAG, "camera kept AE Priority %u - it refused the request", value);
    }
    if (committed != NULL) {
        *committed = value;
    }
    return ESP_OK;
}
```

## Testing

- Both commits compile on their own (`test_app`, esp32s3).
- ESP32-S31 with a UVC H.264 camera, driving the camera's own encoder through the H.264
  Extension Unit and the Camera Terminal: unit located by GUID (`bUnitID 12`), bitrate and
  key-frame period committed exactly as requested, Auto-Exposure Priority set and read back
  in both directions, all surviving four stream restarts during a congestion run.
- The test camera does not implement Generate Key Frame. With the descriptor gate it now
  reports `ESP_ERR_NOT_SUPPORTED` without touching the bus, where before it produced a
  `Dev N EP 0 STALL` at ERROR on every request.

---

## Checklist

- [x] 🚨 This PR does not introduce breaking changes. — purely additive; no existing
      signature or behaviour changes.
- [ ] All CI checks (GH Actions) pass. — not yet run
- [x] Documentation is updated as needed. — doxygen on every new public function, including
      why the VideoStreaming call is an escape hatch. No `CHANGELOG.md` entry yet; tell me
      the form you want.
- [ ] Tests are updated or added as necessary. — none added. The new descriptor lookups are
      pure functions over a configuration descriptor, so `host_test/main/parsing` and its
      per-camera fixtures are the natural home; glad to add cases there.
- [x] Code is well-commented, especially in complex areas.
- [x] Git history is clean — two commits, the API and its first consumer, each compiling on
      its own.

---

> [!NOTE]
> **Medium Risk**
> Touches shared EP0 control transfer behavior and adds new USB class control entry points; mistakes in wValue/wIndex composition or retry semantics could affect all cameras, though changes are mostly additive.
> 
> **Overview**
> Adds a **public control surface** on an open UVC stream so apps can drive VideoControl units/terminals and optional VideoStreaming controls without the private device handle or VideoControl interface number.
> 
> New APIs include descriptor-backed **lookup** (`uvc_host_stream_find_extension_unit`, `uvc_host_stream_find_terminal`), **bmControls/bmaControls capability checks** (`uvc_host_stream_unit_supports_control`), **composed VideoControl requests** (`uvc_host_stream_unit_ctrl`), **raw/custom paths** (`uvc_host_stream_send_custom_request`, `uvc_host_stream_vs_ctrl`), and **`uvc_host_stream_request_key_frame`** with a descriptor gate so unsupported cameras get `ESP_ERR_NOT_SUPPORTED` without a bus STALL.
> 
> Stream open now caches **`uvc_index`** and **`bControlInterfaceNumber`**; descriptor parsing grows VC entity/Extension Unit helpers and safe walks over VideoControl `wTotalLength`.
> 
> **EP0 control path** fixes: buffer size check includes the setup packet; STALL maps to `ESP_ERR_NOT_SUPPORTED`; transient EP0 failures retry a few times (STALL is not retried).
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit e145d7e8660e2e9c701801cfb9f6fc782d35e85f. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

**Comment by ak1932** [comment]
@tore-espressif can you please review this PR as well? The design might require some modifications, hence I have kept it as a draft PR for now. We require it to mainly implement rate control for USB UVC cameras.

**Comment by tore-espressif** [comment]
> @tore-espressif can you please review this PR as well? The design might require some modifications, hence I have kept it as a draft PR for now. We require it to mainly implement rate control for USB UVC cameras.

Will do my best to review this week

File: host/class/uvc/usb_host_uvc/uvc_control.c [hunk 1]
```diff
@@ -217,3 +217,106 @@ esp_err_t uvc_host_stream_control_commit(uvc_host_stream_hdl_t stream_hdl, const
...
     return uvc_control_commit(stream_hdl, &vs_result, vs_format);
 }
+
+/* Generic unit, terminal and VideoStreaming controls */
+
+esp_err_t uvc_host_stream_send_custom_request(uvc_host_stream_hdl_t stream_hdl, uint8_t bmRequestType,
+        uint8_t bRequest, uint16_t wValue, uint16_t wIndex, uint16_t wLength, uint8_t *data)
+{
+    return uvc_host_usb_ctrl(stream_hdl, bmRequestType, bRequest, wValue, wIndex, wLength, data);
+}
```
[the remark this answers is not in the document]
Comment (ak1932) [reply host/class/uvc/usb_host_uvc/uvc_control.c:227]: Fixed

File: host/class/uvc/usb_host_uvc/uvc_descriptor_parsing.c [hunk 2]
```diff
@@ -602,3 +605,201 @@ esp_err_t uvc_desc_get_frame_list(const usb_config_desc_t *config_desc, uint8_t
...
+
+    /* bmaControls is per format: bNumFormats entries of bControlSize bytes. Report the
+     * control as available when any format claims it. */
+    const size_t array_offset = offsetof(uvc_vs_input_header_desc_t, bmaControls);
+    for (uint8_t format = 0; format < vs_header->bNumFormats; format++) {
+        const size_t byte_offset = array_offset + (size_t)format * control_size + byte_index;
+        if (byte_offset >= vs_header->bLength) {
+            break;
+        }
+        if ((vs_header->bmaControls[(size_t)format * control_size + byte_index] >> (control_bit % 8)) & 1) {
```
Comment (tore-espressif) [inline host/class/uvc/usb_host_uvc/uvc_descriptor_parsing.c:799]: Might be more readable
```suggestion
        if ((vs_header->bmaControls[(size_t)format * control_size + byte_index] & BIT(control_bit % 8)) {
```

File: host/class/uvc/usb_host_uvc/uvc_descriptor_parsing.c [hunk 3]
```diff
@@ -602,3 +605,201 @@ esp_err_t uvc_desc_get_frame_list(const usb_config_desc_t *config_desc, uint8_t
...
+    const usb_standard_desc_t *current = (const usb_standard_desc_t *)vc_header;
+    while ((current = usb_parse_next_descriptor_of_type(current, safe_len, UVC_CS_INTERFACE, &offset))) {
+        uint8_t control_size = 0;
+        uint8_t current_id = 0;
+        const uint8_t *bmControls = uvc_desc_unit_bmcontrols(current, &control_size, &current_id);
+        if (!bmControls || current_id != unit_id) {
+            continue;
+        }
+        const uint8_t byte_index = control_bit / 8;
+        *supported = (byte_index < control_size) && ((bmControls[byte_index] >> (control_bit % 8)) & 1);
```
Comment (tore-espressif) [inline host/class/uvc/usb_host_uvc/uvc_descriptor_parsing.c:771]: Might be more readable

```suggestion
        *supported = (byte_index < control_size) && (bmControls[byte_index] & BIT(control_bit % 8));
```

File: host/class/uvc/usb_host_uvc/CHANGELOG.md
Comment (tore-espressif) [inline host/class/uvc/usb_host_uvc/CHANGELOG.md:9]: Might be worth adding `### Added` section that would describe the new feature

File: host/class/uvc/usb_host_uvc/uvc_descriptor_parsing.c [hunk 4]
```diff
@@ -602,3 +605,201 @@ esp_err_t uvc_desc_get_frame_list(const usb_config_desc_t *config_desc, uint8_t
...
+    *id_ret = raw[3]; // bUnitID / bTerminalID sits at the same offset for every unit and terminal
+    return &raw[size_offset + 1];
+}
+
+esp_err_t uvc_desc_get_control_interface_num(const usb_config_desc_t *cfg_desc, uint8_t uvc_index, uint8_t *bInterfaceNumber)
+{
+    UVC_CHECK(cfg_desc && bInterfaceNumber, ESP_ERR_INVALID_ARG);
+    const uvc_vc_header_desc_t *vc_header = uvc_desc_get_control_interface_header(cfg_desc, uvc_index, bInterfaceNumber);
+    return vc_header ? ESP_OK : ESP_ERR_NOT_FOUND;
+}
```
Comment (tore-espressif) [inline host/class/uvc/usb_host_uvc/uvc_descriptor_parsing.c:696]: Do we really need this wrapper? isn't it easier to call `uvc_desc_get_control_interface_header()` directly?

File: host/class/uvc/usb_host_uvc/uvc_descriptor_parsing.c [hunk 5]
```diff
@@ -602,3 +605,201 @@ esp_err_t uvc_desc_get_frame_list(const usb_config_desc_t *config_desc, uint8_t
...
+    UVC_CHECK(cfg_desc && bTerminalID, ESP_ERR_INVALID_ARG);
+
+    const uvc_vc_header_desc_t *vc_header = uvc_desc_get_control_interface_header(cfg_desc, uvc_index, NULL);
+    UVC_CHECK(vc_header, ESP_ERR_NOT_FOUND);
+    const uint16_t safe_len = uvc_desc_get_safe_vc_total_length(cfg_desc, vc_header);
+
+    int offset = 0;
+    const usb_standard_desc_t *current = (const usb_standard_desc_t *)vc_header;
+    while ((current = usb_parse_next_descriptor_of_type(current, safe_len, UVC_CS_INTERFACE, &offset))) {
+        const uint8_t *raw = (const uint8_t *)current;
```
Comment (tore-espressif) [inline host/class/uvc/usb_host_uvc/uvc_descriptor_parsing.c:735]: Would be a lot cleaner if we used an actual descriptor struct like in all other parsing cases

File: host/class/uvc/usb_host_uvc/uvc_control.c [hunk 6]
```diff
@@ -217,3 +217,106 @@ esp_err_t uvc_host_stream_control_commit(uvc_host_stream_hdl_t stream_hdl, const
...
+esp_err_t uvc_host_stream_send_custom_request(uvc_host_stream_hdl_t stream_hdl, uint8_t bmRequestType,
+                                              uint8_t bRequest, uint16_t wValue, uint16_t wIndex, uint16_t wLength, uint8_t *data)
+{
+    return uvc_host_usb_ctrl(stream_hdl, bmRequestType, bRequest, wValue, wIndex, wLength, data);
+}
+
+/**
+ * @brief Fetch the active configuration descriptor of the camera behind this stream
+ */
+static esp_err_t uvc_control_get_cfg_desc(uvc_host_stream_hdl_t stream_hdl, const usb_config_desc_t **cfg_desc)
```
Comment (tore-espressif) [inline host/class/uvc/usb_host_uvc/uvc_control.c:232]: I'm not big fan of wrappers. Will this function add any benefit to the caller?

**Review by tore-espressif — COMMENTED** [review]
@ak1932 The idea and approach look good to me.

Just few comments about implementation

File: host/class/uvc/usb_host_uvc/uvc_descriptor_parsing.c (hunk 4 above)
Comment (ak1932) [reply host/class/uvc/usb_host_uvc/uvc_descriptor_parsing.c]: Yes, I have made uvc_desc_get_control_interface_header non static now 👍

File: host/class/uvc/usb_host_uvc/uvc_descriptor_parsing.c (hunk 5 above)
Comment (ak1932) [reply host/class/uvc/usb_host_uvc/uvc_descriptor_parsing.c]: I have made descriptor structs for common head for input / output terminal and for unit descriptor like other parsing cases

File: host/class/uvc/usb_host_uvc/uvc_control.c (hunk 6 above)
Comment (ak1932) [reply host/class/uvc/usb_host_uvc/uvc_control.c]: Yes this can be discarded

File: host/class/uvc/usb_host_uvc/CHANGELOG.md
Comment (ak1932) [reply host/class/uvc/usb_host_uvc/CHANGELOG.md:9]: Added

File: host/class/uvc/usb_host_uvc/uvc_descriptor_parsing.c (hunk 2 above)
Comment (ak1932) [reply host/class/uvc/usb_host_uvc/uvc_descriptor_parsing.c]: Done

**Comment by ak1932** [comment]
Thanks for the review @tore-espressif! I have addressed all comments and made the PR ready. Do let me know before merge and I'll squash the refactor commits.

**Review by tore-espressif — APPROVED** [review]
@ak1932 thanks, changes LGTM!

If you don't plan any more changes we can proceed with merging

**Comment by ak1932** [comment]
Great! I have squashed the commits and made the PR ready for merging.
